### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Inoplanityanin** [agentd00nut/crossout_crafting_profiter#1]
Error : market_dumper

```
Traceback (most recent call last):
  File "C:\Users\****\Downloads\crossout_crafting_profiter-master\crossout_crafting_profiter-master\market_dumper.py", line 19, in <module>
    faction=data[1];
IndexError: list index out of range
```

pls help with this error,and also i have another one in 

profit_calculator 

```
 RESTART: C:\Users\*****\Downloads\crossout_crafting_profiter-master\crossout_crafting_profiter-master\profit_calculator.py 
Engineer Rares

Traceback (most recent call last):
  File "C:\Users\*****\Downloads\crossout_crafting_profiter-master\crossout_crafting_profiter-master\profit_calculator.py", line 148, in <module>
    find_profits(engineer_rare, "Engineer Rares");
  File "C:\Users\*****\Downloads\crossout_crafting_profiter-master\crossout_crafting_profiter-master\profit_calculator.py", line 142, in find_profits
    price = fetch_price( id )
  File "C:\Users\*****\Downloads\crossout_crafting_profiter-master\crossout_crafting_profiter-master\profit_calculator.py", line 125, in fetch_price
    sell_price = float( j['Item']['FormatSellPrice'] )
KeyError: 'Item'
```

ty 4help

**Comment by agentd00nut** [comment]
Im on vacation so cant look in detail but sounds like the program isnt
finding any data.

I didnt write it to check for errors properly so the array is rmpty and
python is trying to use it, panics, and crashes.

**Comment by agentd00nut** [comment]
Source Website changed their json object keys from all starting with upper case to doing camel casing.

Script checking for valid keys now.

Also fixed error for using "rares" instead of "rare"
